include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disable overly strict rules for initial development
    public_member_api_docs: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/legacy_ui/**"

  errors:
    invalid_annotation_target: ignore
